name: 'Deploy'

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [update_post]

jobs:
  vercel:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
    name: 'Deploy front-end'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Recreate all posts
        shell: bash
        run: |
          npm install --legacy-peer-deps
          npm run build
      - name: 'Deploy to Vercel'
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          working-directory: ./
